# Generated by Django 5.0.6 on 2026-04-21 03:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_institution_institution_prefix'),
        ('trainers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='trainer_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='trainer',
            constraint=models.UniqueConstraint(condition=models.Q(('trainer_code__isnull', False)), fields=('institution', 'trainer_code'), name='unique_trainer_code_per_institution'),
        ),
    ]
