# Generated by Django 5.0.6 on 2026-04-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="province",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
