# Generated by Django 5.0.6 on 2026-04-21 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='institution_prefix',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
