# Generated by Django 5.0.6 on 2026-04-21 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
